# Generated by Django 5.0.4 on 2024-04-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                (
                    "cpf",
                    models.CharField(
                        help_text="000.000.000-00", max_length=14, unique=True
                    ),
                ),
            ],
        ),
    ]
