# Generated by Django 5.0.4 on 2024-04-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="cpf",
            field=models.CharField(
                error_messages={"unique": "CPF ja cadastrado"},
                max_length=14,
                unique=True,
            ),
        ),
    ]
