# Generated by Django 5.0.4 on 2024-04-15 01:41

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_pessoa_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="cpf",
            field=models.CharField(
                error_messages={"unique": "CPF ja cadastrado"},
                max_length=14,
                unique=True,
                validators=[blog.models.verify_cpf],
            ),
        ),
    ]
